# Generated by Django 4.2.2 on 2023-07-05 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0002_rename_exhibition_general_review_movie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviecolumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviecolumns', to=settings.AUTH_USER_MODEL)),
                ('clipping_users', models.ManyToManyField(related_name='clipping_moviecolumns', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_moviecolumns', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviecolumns', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviecolumn_comment', to=settings.AUTH_USER_MODEL)),
                ('moviecolumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moviecolumn.moviecolumn')),
            ],
        ),
    ]
