# Generated by Django 4.2.2 on 2023-07-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_poster'),
        ('moviecolumn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecolumn',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviecolumns', to='movie.movie'),
        ),
    ]
