# Generated by Django 4.2.2 on 2023-07-11 01:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviecolumn', '0002_alter_moviecolumn_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecolumn',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
