# Generated by Django 4.2.2 on 2023-07-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecolumn', '0003_alter_moviecolumn_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecolumn',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
