# Generated by Django 4.2.2 on 2023-07-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_art_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
