# Generated by Django 4.2.2 on 2023-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_art_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
