# Generated by Django 4.2.2 on 2023-07-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
