# Generated by Django 4.2.2 on 2023-07-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_exhibition_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
