# Generated by Django 4.2.2 on 2023-07-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_exhibition_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
