# Generated by Django 4.2.2 on 2023-07-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_followers_user_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='star',
            new_name='stars',
        ),
    ]
