# Generated by Django 4.2.2 on 2023-07-05 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('cast', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=40)),
                ('on_showing', models.BooleanField(default=False)),
                ('ticketing', models.URLField()),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='General_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_general_reviews', to=settings.AUTH_USER_MODEL)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_general_reviews', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Expert_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_expert_reviews', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_expert_reviews', to='movie.movie')),
            ],
        ),
    ]
