# Generated by Django 4.2.2 on 2023-07-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_review',
            old_name='exhibition',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='ticketing',
            field=models.URLField(blank=True),
        ),
    ]
