# Generated by Django 4.2.2 on 2023-07-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_exhibition_general_review_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
