# Generated by Django 4.2.2 on 2023-07-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
