# Generated by Django 4.2.2 on 2023-07-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
